### ISSUE TITLE
CMake or Autotools?

### ISSUE THREAD

**Issue by dontlaugh** [simoncozens/libtexpdf#23]
I see a recently-introduced CMakeLists.txt, but the Github actions workflow doesn't seem to use it.

https://github.com/sile-typesetter/libtexpdf/blob/master/.github/workflows/build.yml#L14

Is cmake just an option for packagers? Is it used when this project is included as a submodule in sile?

**Comment by alerque** [comment]
Autotools.

So the only way we regularly build and test this is as a sub-module of the SILE repository. We use a recursive autotools setup so autotools is used to descend into this project directory and build the library.

The CMake config was a user contribution—if memory serves me as part of the attempt to get a native Windows build working. I believe it worked at some point, but the SILE project's config has not been updated and fell quite a bit behind. I suspect the one in this repository is working or at least very close to working order because not much has changed, but the SILE needs help for sue. We'd be happy to accept contributions that helped fix it up, but none of the developers are on Windows or actively working on that end of things.
