### ISSUE TITLE
We got off64_t wrong

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/libtexpdf#7]
OK, @harrysummer, I think we jumped too soon on this one.

Builds are now failing on 32-bit Linux because it doesn't have off64_t either. We have kludged around the issue on OS X, (because all offsets are 64 bit there) but I worry that we are taking the wrong approach completely.

I am sure the upstream code (dvipdfmx) works on Windows, and so they must have a way of building which does not require using off64_t in the file handling prototypes. I'm going to pull out the off64_t part of your patch (and mine!) while we think about this again.

**Comment by harrysummer** [comment]
I checked the [latest source](https://github.com/TeX-Live/texlive-source/tree/trunk/texk/dvipdfm-x) of dvipdfmx (which is now actively maintained by TexLive). It seems that they are taking the correct (but hard) way.

On Windows, `off_t` is defined in `types.h`:
```c
#ifndef _OFF_T_DEFINED
    #define _OFF_T_DEFINED

    typedef long _off_t; // file offset value

    #if (defined _CRT_DECLARE_NONSTDC_NAMES && _CRT_DECLARE_NONSTDC_NAMES) || (!defined _CRT_DECLARE_NONSTDC_NAMES && !__STDC__)
        typedef _off_t off_t;
    #endif
#endif
```
First, dvipdfmx defined [`__STDC__=1`](https://github.com/TeX-Live/texlive-source/blob/e4619d87166a9b832aab7fbbacf2bda1f438c190/texk/kpathsea/config.h#L58) to ignore the original definition on `off_t`. And then, for Windows platform, it [defines `off_t` to `__int64`](https://github.com/TeX-Live/texlive-source/blob/e4619d87166a9b832aab7fbbacf2bda1f438c190/texk/kpathsea/win32lib.h#L286). It is a hard way because defining `__STDC__` will also ignore other POSIX-compatible definitions. As you can see, they defined all POSIX names in `win32lib.h`.

In my opinion, the correct approach for us might be keeping up-to-date with dvipdfmx by using it as a submodule, and writing our own CMakeLists.txt to build `dvipdfmx` as a library. What do you think?

**Comment by simoncozens** [comment]
Well, I have *something* working at the moment; I added `#include <sys/types.h>` which contains a definition for `off64_t`, and reintroduced the macros which redefine some functions (see a1a23f5). It builds, and SILE seems to pass its tests as well.

It would be ideal to use `dvipdfmx` as a library / submodule, but it is not that simple. I needed to do a lot of work to namespace the functions and untangle the PDF generation stuff from things like the DVI processing code and the kpathsea code. The absolute ideal would be to rewrite dvipdfmx in terms of libtexpdf and submit that upstream. I've had occasional conversations with the TeXLive people about this, and I don't think there's much resistance to the idea, but it would need to be a drop-in replacement for them.

**Comment by harrysummer** [comment]
Great! 32-bit Linux should have a definition of `off64_t` -- it's is designed for accessing large files in 32-bit system where `off_t` is bounded by 2GB size. You can refer to [this stackoverflow answer](https://stackoverflow.com/questions/9073667/where-to-find-the-complete-definition-of-off-t-type/14351239#14351239) for details.

Ideal solution seems a bit tough. TexLive project looks not easy for people to contribute especially because of lacking tools for agility development. We may add that into backlog, but a low priority...

**Comment by simoncozens** [comment]
Yeah, we're building on Linux, OS X and Windows now, so job is done I think.
